#!/bin/bash

#ddev-generated
## Description: Run gulp inside the web container
## Usage: gulp [flags] [args]
## Example: "ddev gulp --version"
## ExecRaw: true

gulp -f="web/themes/ash/gulpfile.js" "$@"
